# 네이버로부터 접근
{
  'wsgi.version': (1,0),
  'wsgi.url_scheme': 'http',
  'wsgi.input': < _io.BufferedReader name = 1248 > ,
  'wsgi.errors': < _io.TextIOWrapper name = '<stderr>'
  mode = 'w'
  encoding = 'utf-8' > ,
  'wsgi.multithread': True,
  'wsgi.multiprocess': False,
  'wsgi.run_once': False,
  'werkzeug.server.shutdown': < function WSGIRequestHandler.make_environ. < locals > .shutdown_server at 0x00000206AD1AA310 > ,
  'SERVER_SOFTWARE': 'Werkzeug/1.0.1',
  'REQUEST_METHOD': 'GET',
  'SCRIPT_NAME': '',
  'PATH_INFO': '/NOTNS',
  'QUERY_STRING': '',
  'REQUEST_URI': '/NOTNS',
  'RAW_URI': '/NOTNS',
  'REMOTE_ADDR': '127.0.0.1',
  'REMOTE_PORT': 58476,
  'SERVER_NAME': '127.0.0.1',
  'SERVER_PORT': '5000',
  'SERVER_PROTOCOL': 'HTTP/1.1',
  'HTTP_HOST': '127.0.0.1: 5000',
  'HTTP_CONNECTION': 'keep-alive',
  'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
  'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
  'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'HTTP_SEC_FETCH_SITE': 'cross-site',
  'HTTP_SEC_FETCH_MODE': 'navigate',
  'HTTP_SEC_FETCH_USER': '?1',
  'HTTP_SEC_FETCH_DEST': 'document',
  'HTTP_REFERER': 'https://blog.naver.com/PostView.nhn?blogId=qusuxu123&Redirect=View&logNo=222110921877&categoryNo=1&isAfterWrite=true&isMrblogPost=false&isHappyBeanLeverage=true&contentLength=180',
  'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
  'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
  'werkzeug.request': < Request 'http://127.0.0.1:5000/NOTNS' [GET] >
}

# 주소창으로부터 접근
{
  'wsgi.version': (1, 0),
  'wsgi.url_scheme': 'http',
  'wsgi.input': < _io.BufferedReader name = 1292 > ,
  'wsgi.errors': < _io.TextIOWrapper name = '<stderr>'
  mode = 'w'
  encoding = 'utf-8' > ,
  'wsgi.multithread': True,
  'wsgi.multiprocess': False,
  'wsgi.run_once': False,
  'werkzeug.server.shutdown': < function WSGIRequestHandler.make_environ. < locals > .shutdown_server at 0x00000206AD1AA790 > ,
  'SERVER_SOFTWARE': 'Werkzeug/1.0.1',
  'REQUEST_METHOD': 'GET',
  'SCRIPT_NAME': '',
  'PATH_INFO': '/NOTNS',
  'QUERY_STRING': '',
  'REQUEST_URI': '/NOTNS',
  'RAW_URI': '/NOTNS',
  'REMOTE_ADDR': '127.0.0.1',
  'REMOTE_PORT': 58636,
  'SERVER_NAME': '127.0.0.1',
  'SERVER_PORT': '5000',
  'SERVER_PROTOCOL': 'HTTP/1.1',
  'HTTP_HOST': '127.0.0.1:5000',
  'HTTP_CONNECTION': 'keep-alive',
  'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
  'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36',
  'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'HTTP_SEC_FETCH_SITE': 'none',
  'HTTP_SEC_FETCH_MODE': 'navigate',
  'HTTP_SEC_FETCH_DEST': 'document',
  'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
  'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
  'werkzeug.request': < Request 'http://127.0.0.1:5000/NOTNS' [GET] >
}